name: A workflow for my Hello World file 1
on: 
  workflow_dispatch:
    inputs:
      name_main:
        description: 'name'     
        required: true
        default: 'Law'  
jobs:
  build:
    name: Hello world action 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: ${{ github.event.inputs.name }} 
